-- MentalTech Discover - Seed Data (7 demo products with full scoring)
-- Ces produits sont presentes a titre d'exemple pour illustrer le catalogue.
-- Les informations n'ont pas ete soumises ni validees par les editeurs.
-- Scores bases sur des recherches publiques (mars 2026), verifies par double recherche.
-- Encoding: UTF-8

-- ============================================================
-- 1. PETIT BAMBOU (64/100 - Grade B)
-- ============================================================
INSERT INTO products (id, name, type, tagline, description, url, logo, tags, audience, problems_solved, preference_match, pricing_model, pricing_amount, pricing_details, last_updated,
  score_security, score_efficacy, score_accessibility, score_ux, score_support,
  justification_security, justification_efficacy, justification_accessibility, justification_ux, justification_support,
  scoring_criteria, audience_priorities, problems_priorities) VALUES
('petitbambou', 'Petit BamBou', 'Application',
 'Application de meditation guidee pour reduire le stress',
 'Application mobile de meditation guidee proposant des centaines de programmes audio pour reduire le stress, ameliorer le sommeil et developper la pleine conscience. Approche accessible pour tous les niveaux avec sessions de 3 a 20 minutes. Plus de 12 millions d''utilisateurs et 510+ seances disponibles. Referencee dans Mon espace sante.',
 'https://www.petitbambou.com', '/logos/petitbambou.png',
 ARRAY['meditation','autonomie','bien-etre','prevention','education'],
 ARRAY['adult','young','senior'],
 ARRAY['stress-anxiety','sleep'],
 ARRAY['autonomous','understand','program'],
 'freemium', NULL,
 'Version gratuite avec programmes decouverte + abonnement premium 69,99 EUR/an. Offres solo, famille, etudiant.',
 '2025-11-20',
 3, 2, 4, 4, 3,
 'RGPD conforme. Hebergement mixte OVH (France) + AWS (region non precisee). Aucune certification ISO 27001 ou HDS publique.',
 'Aucune etude publiee sur PubMed specifique a Petit BamBou. S''appuie sur les principes de la pleine conscience valides, mais sans validation clinique propre a l''application.',
 'iOS, Android, Huawei, web. 6 langues. Version gratuite (programmes decouverte). Offres solo, famille, etudiant. 69,99 EUR/an. Referencee dans Mon espace sante.',
 '12M+ utilisateurs, 510+ seances. Note 4.7/5 App Store (165k evaluations) et Google Play (143k avis). Design reconnu avec animations visuelles.',
 'Support Zendesk + email dedie. Pas d''accompagnement humain personnalise. Pas de communaute integree visible.',
 '{
    "1.1": {"privacy_url": "https://www.petitbambou.com/fr/confidentialite", "has_legal_basis": true, "has_user_rights": true, "has_retention": true, "has_dpo": false},
    "1.2": {"hosting_country": "France + international", "hosting_provider": "OVH + Amazon EC2", "is_hds": false},
    "1.3": {"site_url": "https://www.petitbambou.com", "has_encryption_at_rest": false},
    "1.4": {"cookie_policy": "banner_with_refuse", "cookie_details": "Bandeau cookies conforme avec option de refus"},
    "1.5": {"deletion_method": "self_service", "deletion_details": "Suppression possible via les parametres du compte"},
    "2.1": {"therapeutic_approach": "Pleine conscience (mindfulness), meditation guidee", "approach_url": "https://www.petitbambou.com/fr", "has_scientific_committee": false},
    "2.2": {"study_level": "none", "study_references": "Aucune etude publiee sur PubMed specifique a l''application."},
    "2.3": {"has_professionals": true, "professionals_details": "Contenus crees par des instructeurs de meditation et psychologues"},
    "2.4": {"results_level": "usage_metrics", "results_details": "12 millions d''utilisateurs, 510+ seances disponibles."},
    "3.1": {"pricing_url": "https://www.petitbambou.com/fr", "has_free_tier": true, "has_free_trial": true, "free_trial_duration": "Programmes decouverte gratuits illimites", "has_solidarity_pricing": true, "solidarity_details": "Offre etudiante a tarif reduit"},
    "3.2": {"has_web": true, "web_url": "https://www.petitbambou.com", "has_ios": true, "ios_url": "https://apps.apple.com/fr/app/petit-bambou/id941222646", "has_android": true, "android_url": "https://play.google.com/store/apps/details?id=com.music2relax.petitbambou", "is_native_app": true},
    "3.3": {"french_level": "full_localized", "french_support": true},
    "3.4": {"accessibility_level": "not_evaluated"},
    "3.5": {"onboarding_steps": 3, "onboarding_description": "Telechargement > Inscription > Acces au premier programme gratuit", "has_guided_onboarding": true},
    "4.1": {"homepage_url": "https://www.petitbambou.com", "design_adapted": true, "design_details": "Palette apaisante, animations de respiration, illustrations douces, interface epuree"},
    "4.2": {"nav_clicks": 2, "nav_path": "Accueil > Choisir un programme > Lancer une seance"},
    "4.3": {"main_url_perf": "https://www.petitbambou.com"},
    "4.4": {"content_authors": "Instructeurs de meditation, psychologues", "content_reviewed": true, "content_reviewer": "Equipe interne d''experts en meditation"},
    "4.5": {"mobile_url": "https://www.petitbambou.com", "has_native_mobile": true, "native_ios_url": "https://apps.apple.com/fr/app/petit-bambou/id941222646", "native_android_url": "https://play.google.com/store/apps/details?id=com.music2relax.petitbambou"},
    "5.1": {"contact_url": "https://support.petitbambou.com", "announced_response_time": "Non communique", "support_hours": "Non communique"},
    "5.2": {"has_contact_form": true, "has_email": true, "support_email": "info@petitbambou.com", "has_live_chat": false, "has_phone": false},
    "5.3": {"help_level": "help_center", "help_url": "https://support.petitbambou.com"},
    "5.4": {"crisis_numbers_display": "nowhere"},
    "5.5": {"community_level": "social_media"}
  }'::jsonb,
  '{"P1": ["adult"], "P2": ["young"], "P3": ["senior"]}'::jsonb,
  '{"P1": ["stress-anxiety"], "P2": ["sleep"], "P3": []}'::jsonb);

-- ============================================================
-- 2. KWIT (72/100 - Grade B)
-- ============================================================
INSERT INTO products (id, name, type, tagline, description, url, logo, tags, audience, problems_solved, preference_match, pricing_model, pricing_amount, pricing_details, last_updated,
  score_security, score_efficacy, score_accessibility, score_ux, score_support,
  justification_security, justification_efficacy, justification_accessibility, justification_ux, justification_support,
  scoring_criteria, audience_priorities, problems_priorities) VALUES
('kwit', 'Kwit', 'Application',
 'Arretez de fumer et restez non fumeur pour de bon',
 'Application mobile de sevrage tabagique qui combine TCC et gamification. Accompagne 5 millions d''utilisateurs avec suivi de progression, gestion des envies et contenu educatif. Partenariats avec Imperial College London, Universite Paris-Nanterre et Institut National du Cancer (programme Tabado).',
 'https://kwit.app', '/logos/kwit.png',
 ARRAY['addiction','tabac','sevrage','autonomie','education','prevention','bien-etre'],
 ARRAY['adult','young'],
 ARRAY['addiction'],
 ARRAY['autonomous','understand','program'],
 'freemium', '60€/an',
 'Etude publiee dans JMIR Serious Games 2023. 84% non-fumeurs (enquete 223 utilisateurs, 2022).',
 '2025-11-05',
 3, 4, 4, 4, 3,
 'RGPD conforme avec DPO identifie (Maitre Apolline Schmitt). Siege a Strasbourg (France). Transferts USA reconnus (EU-US Data Privacy Framework). Aucune certification ISO 27001.',
 'Partenariats : Imperial College London, Universite Paris-Nanterre, Institut National du Cancer (programme Tabado). Etude JMIR Serious Games 2023. 84% non-fumeurs (enquete 223 utilisateurs, 2022).',
 'iOS et Android. 4 langues (FR, EN, DE, JA). 5M utilisateurs. Freemium, premium ~60 EUR/an. Version gratuite disponible.',
 'Note App Store 4,6/5 (4,5 selon page About). Gamification : achievements, niveaux, tableau de bord (euros economises, cigarettes evitees). Shake-to-motivate.',
 'Support email (hello@kwit.app). Comite scientifique pluridisciplinaire. Pas de chat en direct ni communaute integree.',
 '{
    "1.1": {"privacy_url": "https://kwit.app/privacy", "has_legal_basis": true, "has_user_rights": true, "has_retention": true, "has_dpo": true, "dpo_name": "Maitre Apolline Schmitt"},
    "1.2": {"hosting_country": "France (donnees locales sur telephone), transferts USA via EU-US DPF", "hosting_provider": "Donnees stockees localement sur appareil", "is_hds": false},
    "1.3": {"site_url": "https://kwit.app", "has_encryption_at_rest": false},
    "1.4": {"cookie_policy": "banner_with_refuse"},
    "1.5": {"deletion_method": "self_service", "deletion_details": "Suppression via parametres du compte dans l''application"},
    "2.1": {"therapeutic_approach": "TCC (Therapie Cognitivo-Comportementale), gamification", "approach_url": "https://kwit.app", "has_scientific_committee": true, "committee_members": "Comite scientifique pluridisciplinaire (psychiatres, psychologues, tabacologues)"},
    "2.2": {"study_level": "peer_reviewed", "study_references": "JMIR Serious Games 2023 - Etude sur gamification et abstinence tabagique. Partenariats : Imperial College London, Universite Paris-Nanterre, INCa (programme Tabado), Sante Respiratoire France."},
    "2.3": {"has_professionals": true, "professionals_details": "Comite scientifique multidisciplinaire supervisant le contenu clinique"},
    "2.4": {"results_level": "satisfaction", "results_details": "Enquete interne 2022 (223 utilisateurs) : 84% non-fumeurs."},
    "3.1": {"pricing_url": "https://kwit.app", "has_free_tier": true, "has_free_trial": false, "has_solidarity_pricing": false},
    "3.2": {"has_web": false, "has_ios": true, "ios_url": "https://apps.apple.com/fr/app/kwit/id577828498", "has_android": true, "android_url": "https://play.google.com/store/apps/details?id=fr.kwit", "is_native_app": true},
    "3.3": {"french_level": "full_localized", "french_support": true},
    "3.4": {"accessibility_level": "not_evaluated"},
    "3.5": {"onboarding_steps": 3, "onboarding_description": "Installation > Inscription > Premier defi/achievement", "has_guided_onboarding": true},
    "4.1": {"homepage_url": "https://kwit.app", "design_adapted": true, "design_details": "Gamification ludique et positive, interface coloree, progression visuelle, ton encourageant"},
    "4.2": {"nav_clicks": 1, "nav_path": "Ouverture app > Dashboard progression + defi du jour"},
    "4.3": {"main_url_perf": "https://kwit.app"},
    "4.4": {"content_authors": "Equipe interne avec supervision du comite scientifique", "content_reviewed": true, "content_reviewer": "Comite scientifique pluridisciplinaire"},
    "4.5": {"mobile_url": "https://kwit.app", "has_native_mobile": true, "native_ios_url": "https://apps.apple.com/fr/app/kwit/id577828498", "native_android_url": "https://play.google.com/store/apps/details?id=fr.kwit"},
    "5.1": {"contact_url": "https://kwit.app", "announced_response_time": "Non communique", "support_hours": "Non communique"},
    "5.2": {"has_contact_form": false, "has_email": true, "support_email": "hello@kwit.app", "has_live_chat": false, "has_phone": false},
    "5.3": {"help_level": "good_faq", "help_url": "https://kwit.app"},
    "5.4": {"crisis_numbers_display": "nowhere"},
    "5.5": {"community_level": "social_media"}
  }'::jsonb,
  '{"P1": ["adult"], "P2": ["young"], "P3": []}'::jsonb,
  '{"P1": ["addiction"], "P2": [], "P3": []}'::jsonb);

-- ============================================================
-- 3. SOBERO (64/100 - Grade B)
-- ============================================================
INSERT INTO products (id, name, type, tagline, description, url, logo, tags, audience, problems_solved, preference_match, pricing_model, pricing_amount, pricing_details, last_updated,
  score_security, score_efficacy, score_accessibility, score_ux, score_support,
  justification_security, justification_efficacy, justification_accessibility, justification_ux, justification_support,
  scoring_criteria, audience_priorities, problems_priorities) VALUES
('sobero', 'Sobero', 'Application',
 'Reprenez le pouvoir sur votre consommation d''alcool, en toute conscience et bienveillance.',
 'Application mobile qui aide a developper une relation plus saine avec l''alcool, basee sur la science du comportement et la gamification. Propose un accompagnement anonyme et bienveillant avec suivi de consommation, exercices de journaling, communaute d''entraide et contenu educatif. Developpee par l''equipe Kwit.',
 'https://sobero.app', '/logos/sobero.png',
 ARRAY['addiction','alcool','sevrage','autonomie','education','prevention','bien-etre'],
 ARRAY['adult','young'],
 ARRAY['addiction'],
 ARRAY['autonomous','understand','program'],
 'subscription', '60€/an',
 '7 jours d''essai gratuits. Disponible sur iOS uniquement. Note App Store 4,5/5.',
 '2025-11-05',
 3, 3, 3, 4, 3,
 'RGPD conforme. Politique de confidentialite actuellement en 404. Aucune certification HDS ou ISO 27001 mentionnee. Hebergeur non precise. Developpe par Kwit (Strasbourg).',
 'Base science du comportement et gamification. Comite scientifique non verifiable publiquement sur le site. Evaluee positivement par AppSanteMentale.ca. Aucune etude clinique publiee specifique.',
 'iOS uniquement (pas de version Android confirmee). 59,99 EUR/an avec 7 jours d''essai gratuit. Francais et anglais. L''absence d''Android exclut ~70% du marche FR.',
 'Note App Store 4,5/5 (251 avis). Interface soignee, suivi quotidien, defis engageants, graphiques detailles. Communaute integree bienveillante.',
 'Communaute peer-to-peer integree. Chat expert in-app (premium). Email hello@sobero.app + FAQ. Pas de hotline ni d''accompagnement therapeutique individuel.',
 '{
    "1.1": {"privacy_url": "https://sobero-prod.web.app/en/privacyPolicy.html", "has_legal_basis": true, "has_user_rights": true, "has_retention": true, "has_dpo": false},
    "1.2": {"hosting_country": "Union Europeenne (a verifier - page confidentialite en 404)", "hosting_provider": "Non precise publiquement", "is_hds": false},
    "1.3": {"site_url": "https://sobero.app", "has_encryption_at_rest": false},
    "1.4": {"cookie_policy": "banner_with_refuse"},
    "1.5": {"deletion_method": "self_service", "deletion_details": "Suppression du compte via les parametres de l''application"},
    "2.1": {"therapeutic_approach": "Science du comportement, gamification", "approach_url": "https://sobero.app", "has_scientific_committee": false},
    "2.2": {"study_level": "none", "study_references": "Aucune etude clinique publiee specifique a Sobero. Evaluee positivement par AppSanteMentale.ca."},
    "2.3": {"has_professionals": false},
    "2.4": {"results_level": "usage_metrics", "results_details": "Metriques d''engagement (jours sobres consecutifs, suivi consommation). Pas de resultats cliniques publies."},
    "3.1": {"pricing_url": "https://sobero.app", "has_free_tier": false, "has_free_trial": true, "free_trial_duration": "7 jours", "has_solidarity_pricing": false},
    "3.2": {"has_web": false, "has_ios": true, "ios_url": "https://apps.apple.com/fr/app/drinking-control-sobero/id6443543144", "has_android": false, "is_native_app": true},
    "3.3": {"french_level": "full_content", "french_support": true},
    "3.4": {"accessibility_level": "not_evaluated"},
    "3.5": {"onboarding_steps": 3, "onboarding_description": "Telechargement > Inscription > Parametrage objectifs > Premier suivi quotidien", "has_guided_onboarding": true},
    "4.1": {"homepage_url": "https://sobero.app", "design_adapted": true, "design_details": "Ton bienveillant et non stigmatisant. Interface de suivi quotidien claire. Gamification positive."},
    "4.2": {"nav_clicks": 1, "nav_path": "Ouverture app > Dashboard quotidien avec suivi et defi du jour"},
    "4.3": {"main_url_perf": "https://sobero.app"},
    "4.4": {"content_authors": "Equipe interne Kwit", "content_reviewed": false},
    "4.5": {"mobile_url": "https://sobero.app", "has_native_mobile": true, "native_ios_url": "https://apps.apple.com/fr/app/drinking-control-sobero/id6443543144"},
    "5.1": {"contact_url": "https://sobero.app", "announced_response_time": "Non communique", "support_hours": "Non communique"},
    "5.2": {"has_contact_form": false, "has_email": true, "support_email": "hello@sobero.app", "has_live_chat": true, "chat_url": "In-app (premium)", "has_phone": false},
    "5.3": {"help_level": "good_faq", "help_url": "https://sobero.app"},
    "5.4": {"crisis_numbers_display": "nowhere"},
    "5.5": {"community_level": "active_community", "community_url": "Communaute peer-to-peer integree dans l''application"}
  }'::jsonb,
  '{"P1": ["adult"], "P2": ["young"], "P3": []}'::jsonb,
  '{"P1": ["addiction"], "P2": [], "P3": []}'::jsonb);

-- ============================================================
-- 4. LET''S TOLK (64/100 - Grade B)
-- ============================================================
INSERT INTO products (id, name, type, tagline, description, url, logo, tags, audience, problems_solved, preference_match, pricing_model, pricing_amount, pricing_details, last_updated,
  score_security, score_efficacy, score_accessibility, score_ux, score_support,
  justification_security, justification_efficacy, justification_accessibility, justification_ux, justification_support,
  scoring_criteria, audience_priorities, problems_priorities) VALUES
('letstolk', 'Let''s Tolk', 'Teleconsultation',
 'Les psychologues en ligne',
 'Cabinet digital de psychologues en ligne diplomes d''un Master en psychologie (5 ans). Accompagnement humain, professionnel et attentif en visio et messagerie pour burn-out, anxiete, depression, troubles du sommeil et addictions. Entreprise a mission basee a Lille.',
 'https://www.letstolk.com/', '/logos/letstolk.svg',
 ARRAY['professionnel','teleconsultation','prevention','urgent'],
 ARRAY['adult','young','senior','parent'],
 ARRAY['stress-anxiety','sadness','addiction','trauma','work','sleep'],
 ARRAY['talk-now'],
 'per-session', 'a partir de 23€',
 'Mini-Consult 23 EUR (20 min), standard a partir de 49 EUR (45 min). Remboursement mutuelle possible.',
 '2025-11-05',
 3, 3, 4, 3, 3,
 'Psychologues diplomes Master psychologie (5 ans). Plateforme de teleconsultation (site Wix). Aucune certification HDS ou ISO 27001 documentee. SAS a Lille, SIREN 951 988 146.',
 'Psychologues diplomes avec minimum 3 ans d''experience (~20 psychologues). Approches variees. Pas d''etude d''impact publiee. Environ 100 patients suivis (2024).',
 'Mini-Consult 23 EUR (20 min), standard a partir de 49 EUR (45 min). Remboursement mutuelle possible (pas Mon Soutien Psy). Teleconsultation video + messagerie.',
 'Site Wix, pas d''app native (potentiellement PWA). Aucun avis client public trouve. Interface web simple pour la prise de RDV.',
 'Accompagnement par psychologues professionnels. Messagerie ecrite et vocale asynchrone entre seances. Pas de FAQ structuree.',
 '{
    "1.1": {"privacy_url": "https://www.letstolk.com/mentions-legales", "has_legal_basis": true, "has_user_rights": true, "has_retention": false, "has_dpo": false},
    "1.2": {"hosting_country": "Non precise publiquement", "hosting_provider": "Wix (hebergement integre)", "is_hds": false},
    "1.3": {"site_url": "https://www.letstolk.com", "has_encryption_at_rest": false},
    "1.4": {"cookie_policy": "banner_with_refuse"},
    "1.5": {"deletion_method": "email_only", "deletion_details": "Contactez le support pour supprimer votre compte"},
    "2.1": {"therapeutic_approach": "Psychologues cliniciens diplomes - approches variees (TCC, psychodynamique, systemique, EMDR)", "approach_url": "https://www.letstolk.com", "has_scientific_committee": false},
    "2.2": {"study_level": "none", "study_references": "Pas d''etude d''impact publiee specifique a Let''s Tolk."},
    "2.3": {"has_professionals": true, "professionals_details": "Psychologues diplomes Master psychologie (5 ans d''etudes), minimum 3 ans d''experience."},
    "2.4": {"results_level": "testimonials", "results_details": "Temoignages utilisateurs sur le site. Environ 100 patients suivis en 2024."},
    "3.1": {"pricing_url": "https://www.letstolk.com", "has_free_tier": false, "has_free_trial": false, "has_solidarity_pricing": false},
    "3.2": {"has_web": true, "web_url": "https://www.letstolk.com", "has_ios": false, "has_android": false, "is_native_app": false},
    "3.3": {"french_level": "full_localized", "french_support": true},
    "3.4": {"accessibility_level": "not_evaluated"},
    "3.5": {"onboarding_steps": 3, "onboarding_description": "Choisir un creneau > Choisir un psychologue > Teleconsultation", "has_guided_onboarding": false},
    "4.1": {"homepage_url": "https://www.letstolk.com", "design_adapted": true, "design_details": "Interface sobre et professionnelle adaptee a un contexte therapeutique"},
    "4.2": {"nav_clicks": 2, "nav_path": "Accueil > Prendre rendez-vous > Selection creneau et psychologue"},
    "4.3": {"main_url_perf": "https://www.letstolk.com"},
    "4.4": {"content_authors": "Equipe Let''s Tolk", "content_reviewed": false},
    "4.5": {"mobile_url": "https://www.letstolk.com", "has_native_mobile": false},
    "5.1": {"contact_url": "https://www.letstolk.com/contact", "announced_response_time": "Non communique", "support_hours": "Non communique"},
    "5.2": {"has_contact_form": true, "contact_form_url": "https://www.letstolk.com/contact", "has_email": false, "has_live_chat": false, "has_phone": false},
    "5.3": {"help_level": "minimal_faq"},
    "5.4": {"crisis_numbers_display": "footer"},
    "5.5": {"community_level": "none"}
  }'::jsonb,
  '{"P1": ["adult"], "P2": ["young"], "P3": ["parent"]}'::jsonb,
  '{"P1": ["stress-anxiety"], "P2": ["trauma"], "P3": ["addiction"]}'::jsonb);

-- ============================================================
-- 5. FEEL (64/100 - Grade B)
-- ============================================================
INSERT INTO products (id, name, type, tagline, description, url, logo, tags, audience, problems_solved, preference_match, pricing_model, pricing_amount, pricing_details, last_updated,
  score_security, score_efficacy, score_accessibility, score_ux, score_support,
  justification_security, justification_efficacy, justification_accessibility, justification_ux, justification_support,
  scoring_criteria, audience_priorities, problems_priorities) VALUES
('feel', 'Feel', 'Application',
 'Feel est une application qui aide a soigner la depression en 3 a 6 mois.',
 'Application qui aide a soigner la depression en 3 a 6 mois basee sur la therapie cognitivo-comportementale. Accompagne les utilisateurs pour modifier leurs comportements et maitriser leurs pensees negatives avec des exercices pratiques, outils TCC (PHQ-9, GAD-7, HAMD-21) et contenu de psychoeducation. Certification ISO 27001.',
 'https://feelapp.care/', '/logos/feel.png',
 ARRAY['autonomie','education','prevention','bien-etre','urgent'],
 ARRAY['adult','senior','parent'],
 ARRAY['sadness'],
 ARRAY['autonomous','understand','program'],
 'freemium', '9,99€/mois ou 29,99€/6 mois',
 '85+ seances TCC/ACT gratuites sans limite. Essai premium 15 jours. Note App Store 4,7/5.',
 '2025-11-12',
 3, 2, 4, 4, 3,
 'ISO 27001 declare sur le site. Donnees chiffrees et anonymisees. Aucune certification HDS ni precision sur l''hebergement. FEEL SAS, RCS Nanterre 918866716.',
 'Protocole TCC en 5 composantes developpe avec psychiatres. Outils valides integres (PHQ-9, GAD-7, HAMD-21, CBI). Etude enregistree au Health Data Hub (mai-dec 2024), resultats non publies.',
 'iOS et Android. 85+ seances TCC/ACT gratuites sans limite. Premium 9,99 EUR/mois ou 29,99 EUR/6 mois. Essai 15 jours. Francais uniquement.',
 'Note App Store 4,7/5 (153 avis). 37k+ telechargements. Parcours TCC progressif structure avec suivi de l''humeur et exercices personnalises.',
 'Email (hello@feelapp.care). Reference 3114. Q&A asynchrone avec psychiatres en premium. Pas de chat en direct.',
 '{
    "1.1": {"privacy_url": "https://feelapp.care/legal", "has_legal_basis": true, "has_user_rights": true, "has_retention": true, "has_dpo": false},
    "1.2": {"hosting_country": "Non precise publiquement", "hosting_provider": "Non precise publiquement", "is_hds": false},
    "1.3": {"site_url": "https://feelapp.care", "has_encryption_at_rest": true, "encryption_tech": "ISO 27001 certifie - details techniques non publics"},
    "1.4": {"cookie_policy": "banner_with_refuse"},
    "1.5": {"deletion_method": "self_service", "deletion_details": "Suppression du compte disponible dans l''application"},
    "2.1": {"therapeutic_approach": "TCC (Therapie Cognitivo-Comportementale), ACT (Therapie d''Acceptation et d''Engagement)", "approach_url": "https://feelapp.care/science", "has_scientific_committee": true, "committee_members": "Psychiatres et psychologues (noms non publies sur le site)"},
    "2.2": {"study_level": "internal", "study_references": "Etude enregistree au Health Data Hub (mai-dec 2024). Resultats non publies."},
    "2.3": {"has_professionals": true, "professionals_details": "Q&A avec psychiatres (premium). Protocole developpe avec des professionnels de sante mentale."},
    "2.4": {"results_level": "clinical_outcomes", "results_details": "Outils d''evaluation cliniques valides integres : PHQ-9, GAD-7, HAMD-21, CBI."},
    "3.1": {"pricing_url": "https://feelapp.care", "has_free_tier": true, "has_free_trial": true, "free_trial_duration": "15 jours", "has_solidarity_pricing": false},
    "3.2": {"has_web": false, "has_ios": true, "ios_url": "https://apps.apple.com/fr/app/feel-soigner-la-depression/id6444725595", "has_android": true, "android_url": "https://play.google.com/store/apps/details?id=com.feelmobile", "is_native_app": true},
    "3.3": {"french_level": "full_localized", "french_support": true},
    "3.4": {"accessibility_level": "not_evaluated"},
    "3.5": {"onboarding_steps": 3, "onboarding_description": "Telechargement > Inscription > Questionnaire initial (PHQ-9) > Programme personnalise", "has_guided_onboarding": true},
    "4.1": {"homepage_url": "https://feelapp.care", "design_adapted": true, "design_details": "Interface concue pour un public depressif : ton empathique, couleurs douces, pas de surcharge cognitive"},
    "4.2": {"nav_clicks": 2, "nav_path": "Ouverture app > Questionnaire humeur > Exercice TCC recommande"},
    "4.3": {"main_url_perf": "https://feelapp.care"},
    "4.4": {"content_authors": "Equipe clinique interne (psychiatres et psychologues)", "content_reviewed": true, "content_reviewer": "Equipe de psychiatres"},
    "4.5": {"mobile_url": "https://feelapp.care", "has_native_mobile": true, "native_ios_url": "https://apps.apple.com/fr/app/feel-soigner-la-depression/id6444725595", "native_android_url": "https://play.google.com/store/apps/details?id=com.feelmobile"},
    "5.1": {"contact_url": "https://feelapp.care", "announced_response_time": "Non communique", "support_hours": "Non communique"},
    "5.2": {"has_contact_form": false, "has_email": true, "support_email": "hello@feelapp.care", "has_live_chat": false, "has_phone": false},
    "5.3": {"help_level": "minimal_faq"},
    "5.4": {"crisis_numbers_display": "interface_visible", "crisis_detection": false},
    "5.5": {"community_level": "none"}
  }'::jsonb,
  '{"P1": ["adult"], "P2": ["parent"], "P3": ["young"]}'::jsonb,
  '{"P1": ["sadness"], "P2": ["stress-anxiety"], "P3": ["sleep"]}'::jsonb);

-- ============================================================
-- 6. HYPNOVR (72/100 - Grade B)
-- ============================================================
INSERT INTO products (id, name, type, tagline, description, url, logo, tags, audience, problems_solved, preference_match, pricing_model, pricing_amount, pricing_details, last_updated,
  score_security, score_efficacy, score_accessibility, score_ux, score_support,
  justification_security, justification_efficacy, justification_accessibility, justification_ux, justification_support,
  scoring_criteria, audience_priorities, problems_priorities) VALUES
('hypnovr', 'HypnoVR', 'Dispositif medical',
 'Ameliorer son parcours de soin grace a son cerveau !',
 'Therapies digitales certifiees en realite virtuelle pour la sante mentale. Propose des seances d''hypnose immersives pour gerer le stress, l''anxiete, les troubles du sommeil et la douleur. Plus de 300 etablissements de sante equipes avec 23 etudes cliniques publiees. Partenaires : Mayo Clinic, AP-HP, Sorbonne. Certifie ISO 27001 depuis 2023.',
 'https://hypnovr.io/', '/logos/hypnovr.png',
 ARRAY['bien-etre','entreprise'],
 ARRAY['adult','young','child','senior'],
 ARRAY['stress-anxiety','work','sleep','douleur'],
 ARRAY['autonomous','program'],
 'subscription', NULL,
 'Abonnement pour etablissements de sante. Dispositif Medical certifie ISO 13485, Classe 1 (CE).',
 '2025-11-17',
 4, 4, 3, 4, 3,
 'ISO 13485 + ISO 27001 (depuis sept 2023). Dispositif Medical Classe 1 (CE). Brevet europeen janvier 2024. RGPD conforme. Hebergeur non precise publiquement.',
 '23 etudes cliniques publiees, 37 en cours. Partenaires : Mayo Clinic, AP-HP, Sorbonne, CHU Rouen, Bordeaux, Strasbourg. 68% reduction douleur, 93% reduction sedatifs (Mayo Clinic).',
 'B2B uniquement (etablissements de sante). 300+ etablissements equipes (500+ annonce sur site FR mais 300+ sur EN/DE). Site FR/EN/DE. Aucun tarif public.',
 'Lancement seances < 30 secondes. Environnements 3D HD personnalisables. 90-100% satisfaction patients et soignants dans les etudes. Solution cle en main.',
 'Accompagnement deploiement avec equipes regionales. Telephone direct (+33 3 73 80 00 33). Pas de programme de formation structure documente publiquement.',
 '{
    "1.1": {"privacy_url": "https://hypnovr.io/fr/politique-de-confidentialite/", "has_legal_basis": true, "has_user_rights": true, "has_retention": false, "has_dpo": false},
    "1.2": {"hosting_country": "Non precise publiquement", "hosting_provider": "Non precise publiquement", "is_hds": false},
    "1.3": {"site_url": "https://hypnovr.io", "has_encryption_at_rest": false},
    "1.4": {"cookie_policy": "banner_with_refuse"},
    "1.5": {"deletion_method": "email_only", "deletion_details": "Contact direct necessaire (B2B, pas de compte utilisateur individuel)"},
    "2.1": {"therapeutic_approach": "Hypnose medicale en realite virtuelle (VR), hypnoanalgesia, relaxation immersive", "approach_url": "https://hypnovr.io/fr/recherche/", "has_scientific_committee": true, "committee_members": "Dr Denis Graff (anesthesiste-reanimateur), Dr Chloe Chauvin (anesthesiste-reanimatrice), Nicolas Schaettel (President)"},
    "2.2": {"study_level": "peer_reviewed", "study_references": "23 etudes publiees, 37 en cours. Mayo Clinic, AP-HP, Sorbonne, CHU Rouen, Bordeaux, Strasbourg. 68% reduction douleur, 93% reduction sedatifs, 45% reduction morphine."},
    "2.3": {"has_professionals": true, "professionals_details": "Cofonde par 2 medecins anesthesistes. Utilise exclusivement par des professionnels de sante en milieu hospitalier."},
    "2.4": {"results_level": "clinical_outcomes", "results_details": "90-100% satisfaction patients. 91-100% satisfaction soignants. 300+ etablissements equipes couvrant 30+ specialites."},
    "3.1": {"pricing_url": "https://hypnovr.io/fr/contact/", "has_free_tier": false, "has_free_trial": true, "free_trial_duration": "Demonstration sur demande pour etablissements", "has_solidarity_pricing": false},
    "3.2": {"has_web": false, "has_ios": false, "has_android": false, "is_native_app": false},
    "3.3": {"french_level": "full_localized", "french_support": true},
    "3.4": {"accessibility_level": "not_evaluated"},
    "3.5": {"onboarding_steps": 1, "onboarding_description": "Deploiement professionnel : mise en place du casque VR > lancement de seance en < 30 secondes", "has_guided_onboarding": true},
    "4.1": {"homepage_url": "https://hypnovr.io", "design_adapted": true, "design_details": "Environnements 3D HD apaisants avec paysages sonores multiples."},
    "4.2": {"nav_clicks": 1, "nav_path": "Mise en place casque > Selection environnement > Lancement seance (< 30 sec total)"},
    "4.3": {"main_url_perf": "https://hypnovr.io"},
    "4.4": {"content_authors": "Equipe medicale interne (co-fondateurs medecins)", "content_reviewed": true, "content_reviewer": "Dr Denis Graff et Dr Chloe Chauvin"},
    "4.5": {"mobile_url": "https://hypnovr.io", "has_native_mobile": false},
    "5.1": {"contact_url": "https://hypnovr.io/fr/contact/", "announced_response_time": "Non communique", "support_hours": "Non communique"},
    "5.2": {"has_contact_form": true, "contact_form_url": "https://hypnovr.io/fr/contact/", "has_email": false, "has_live_chat": false, "has_phone": true, "phone_number": "+33 3 73 80 00 33"},
    "5.3": {"help_level": "minimal_faq"},
    "5.4": {"crisis_numbers_display": "nowhere"},
    "5.5": {"community_level": "none"}
  }'::jsonb,
  '{"P1": ["adult"], "P2": ["young"], "P3": []}'::jsonb,
  '{"P1": ["stress-anxiety"], "P2": ["sleep"], "P3": []}'::jsonb);

-- ============================================================
-- 7. MOKA.CARE (72/100 - Grade B)
-- ============================================================
INSERT INTO products (id, name, type, tagline, description, url, logo, tags, audience, problems_solved, preference_match, pricing_model, pricing_amount, pricing_details, last_updated,
  score_security, score_efficacy, score_accessibility, score_ux, score_support,
  justification_security, justification_efficacy, justification_accessibility, justification_ux, justification_support,
  scoring_criteria, audience_priorities, problems_priorities) VALUES
('mokacare', 'moka.care', 'Plateforme entreprise',
 'Plateforme de sante mentale pour accompagner les salaries',
 'Solution complete de sante mentale en entreprise proposant un accompagnement par psychologues, therapeutes et coachs. Presente dans 320+ entreprises et 20 pays. Hebergement via infrastructure certifiee HDS, ISO 27001, SOC 2/3 (Heroku). Certification Qualiopi pour les formations.',
 'https://www.moka.care', '/logos/mokacare.png',
 ARRAY['professionnel','entreprise','teleconsultation','prevention','accompagnement','bien-etre'],
 ARRAY['entreprise'],
 ARRAY['work','stress-anxiety','sadness'],
 ARRAY['talk-now','program','understand'],
 'enterprise', NULL,
 'Sur devis pour entreprises. Formations eligibles OPCO.',
 '2025-11-20',
 4, 3, 4, 3, 4,
 'Hebergement Europe via Heroku (certifie ISO 27001, SOC 2/3, HDS - certifications de l''hebergeur, pas de moka.care). Chiffrement AES-256 au repos, HTTPS/TLS. Dashboards RH anonymises. RGPD complet.',
 '80% des collaborateurs se sentent mieux. 1/3 aurait evite un burnout. 15% d''utilisation (vs 0,5-1% EAP). Partenariat GHU Paris + Ifop. Pas d''etude clinique RCT publiee.',
 '20 pays, 25+ langues, 320+ entreprises (L''Oreal, BlaBlaCar, Qonto). Formations eligibles OPCO. Tarification non publique (sur devis).',
 'Temoignages DRH positifs (Partoo, Qonto, PlayPlay). 800+ contenus. Pas de notes verifiables sur Trustpilot/G2.',
 'Consultant prevention dedie par entreprise. Kit de lancement personnalise. Dashboard RH anonymise. Formations managers. Certification Qualiopi.',
 '{
    "1.1": {"privacy_url": "https://www.moka.care/privacy", "has_legal_basis": true, "has_user_rights": true, "has_retention": true, "has_dpo": true, "dpo_name": "Non precise publiquement"},
    "1.2": {"hosting_country": "Europe", "hosting_provider": "Heroku (certifie ISO 27001, SOC 2/3, HDS) + OVH", "is_hds": true},
    "1.3": {"site_url": "https://www.moka.care", "has_encryption_at_rest": true, "encryption_tech": "AES-256"},
    "1.4": {"cookie_policy": "banner_with_refuse"},
    "1.5": {"deletion_method": "documented", "deletion_details": "Droits d''acces et suppression documentes dans la politique de confidentialite"},
    "2.1": {"therapeutic_approach": "Approche pluridisciplinaire : psychologues, therapeutes, coachs, psychiatres", "approach_url": "https://www.moka.care", "has_scientific_committee": true, "committee_members": "Equipe clinique supervisee. Partenariat GHU Paris Psychiatrie & Neurosciences."},
    "2.2": {"study_level": "internal", "study_references": "Grande Enquete 2025 avec GHU Paris + Ifop (2200 repondants). Pas de publication peer-reviewed."},
    "2.3": {"has_professionals": true, "professionals_details": "Reseau de praticiens selectionnes (5% des candidats acceptes, moyenne 10 ans d''experience)."},
    "2.4": {"results_level": "satisfaction", "results_details": "80% des collaborateurs plus epanouis. 1/3 aurait evite un burnout. 15% taux d''utilisation moyen."},
    "3.1": {"pricing_url": "https://www.moka.care", "has_free_tier": false, "has_free_trial": false, "has_solidarity_pricing": false},
    "3.2": {"has_web": true, "web_url": "https://www.moka.care", "has_ios": true, "has_android": true, "is_native_app": true},
    "3.3": {"french_level": "full_localized", "french_support": true},
    "3.4": {"accessibility_level": "not_evaluated"},
    "3.5": {"onboarding_steps": 3, "onboarding_description": "Activation par l''entreprise > Inscription collaborateur > Matching avec praticien", "has_guided_onboarding": true},
    "4.1": {"homepage_url": "https://www.moka.care", "design_adapted": true, "design_details": "Interface professionnelle et bienveillante. Portail salarie distinct du portail RH. 800+ contenus structures."},
    "4.2": {"nav_clicks": 2, "nav_path": "Connexion > Selection praticien/contenu > Prise de RDV ou acces contenu"},
    "4.3": {"main_url_perf": "https://www.moka.care"},
    "4.4": {"content_authors": "Equipe clinique pluridisciplinaire et redacteurs specialises", "content_reviewed": true, "content_reviewer": "Equipe clinique moka.care"},
    "4.5": {"mobile_url": "https://www.moka.care", "has_native_mobile": true},
    "5.1": {"contact_url": "https://www.moka.care/contact", "announced_response_time": "Non communique", "support_hours": "Non communique"},
    "5.2": {"has_contact_form": true, "contact_form_url": "https://www.moka.care/contact", "has_email": true, "support_email": "hello@moka.care", "has_live_chat": false, "has_phone": false},
    "5.3": {"help_level": "help_center"},
    "5.4": {"crisis_numbers_display": "interface_visible", "crisis_detection": false},
    "5.5": {"community_level": "none"}
  }'::jsonb,
  '{"P1": ["entreprise"], "P2": [], "P3": []}'::jsonb,
  '{"P1": ["work"], "P2": ["sadness"], "P3": []}'::jsonb);

-- Tous les produits du seed sont des exemples de demonstration
UPDATE products SET is_demo = TRUE;
